### ISSUE TITLE
Whitelist & Blacklist of 3rd-party dependencies

### ISSUE THREAD

**Issue by hezean** [hezean/chatting#3]
Per the document mentioned, we will allow you to use some dependencies to simplify your coding.

Here's a list of what you can use and what you cannot:

| Classification | Library      | Limitations |
| :------------: | :----------: | :---------: |
| JavaFX         | FormsFX, ControlFX, bootstrapFX...      | ✅ |
| Socket         | socket.io / engine.io / netty-socketio... | ❌ we want you to use raw socket and reader/writer |
| Database        | any      | ✅ |
| Misc           | Lombok       | ✅ |
| Misc           | Guava        | ✅ |
| Misc           | jackson-databind or other JSON-related libs | ✅ |

_You can ask below for the library you are interested in and we will let you know if you can use it after a discussion._

**Comment by NoMathExpectation** [comment]
能使用HTTP进行通信吗？使用库呢？

**Comment by hezean** [comment]
> 能使用HTTP进行通信吗？使用库呢？

不允许对 socket 通信进行封装，你需要在 socket/serversocket 的基础上用 reader/writer 实现自己的协议
但是在 reader/writer 之上的更高级的抽象层面允许使用一些第三方库

**Comment by MuuuShin** [comment]
允许使用javaFX的其他三方库扩展吗，如ControlFX或者bootstrapFX？

**Comment by hezean** [comment]
> 允许使用javaFX的其他三方库扩展吗，如ControlFX或者bootstrapFX？

可以 @MuuuShin
