### ISSUE TITLE
Cannot run demo Client: Unrecognized option: --module-path

### ISSUE THREAD

**Issue by skylynf** [hezean/chatting#4]
I followed the instruction of demo readme file, however, when using javafx plugin to run client in demo, it says that
```
Unrecognized option: --module-path
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```
And I've tried several method to fix it, including reclone git respository and changing versions of JDK, but nothing works.
I cannot find parameter `--module-path` in javafx:run or pom.xml file.

**Comment by hezean** [comment]
Please provide the output of `java -version` and the way you use maven (installed locally or maven wrapper)

**Comment by skylynf** [comment]
Thanks, problem fixed.
When using maven in IDEA, it follows the system path jdk instead of assigned JDK in idea. My system path jdk is still old version 1.8, it doesn't have --module-path args. Simply change system path to newer version jdk can fix the problem.
Thanks a lot for providing advise with fixing the problem.
