### ISSUE TITLE
In template `Controller.java` , Not doing set Null operation may cause display issues

### ISSUE THREAD

**Issue by skylynf** [hezean/chatting#5]
In template 'Controller.java' line 115
`private class MessageCellFactory`
```
if (empty || Objects.isNull(msg)) {
    return;
}
```
Can be modified to
```
if (empty || Objects.isNull(msg)) {
    setText(null);
    setGraphic(null);
    return;
}
```
to fix some display issue.

**Comment by hezean** [comment]
Thanks, resolved by https://github.com/hezean/chatting/commit/0c9b3a017c065249ab09ab915aaf61b87976c880
